- name: download kibana
  get_url:
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.9.2-amd64.deb
    dest: /tmp

- name: Установка kibana
  apt:
    deb: /tmp/kibana-8.9.2-amd64.deb

- name: kibana cfg
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: '#elasticsearch.hosts: ["http://localhost:9200"]', line: 'elasticsearch.hosts: ["http://192.168.30.101:9200"]'}
    - { regexp: '#server.host: "localhost"', line: 'server.host: 0.0.0.0'}

- name: restart kibana
  systemd:
    name: kibana
    enabled: yes
    state: restarted
