- name: download elasticsearch 
  get_url:
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.9.2-amd64.deb
    dest: /tmp

- name: install elasticsearch
  apt:
    deb: /tmp/elasticsearch-8.9.2-amd64.deb

- name: copy cfg
  copy:
    src: ../templates/elasticsearch.yml
    dest: /etc/elasticsearch
    mode: 0660
    owner: root
    group: elasticsearch

- name: run elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
